version: "3.10"

services:
  redis:
    image: redis:latest
    container_name: rd01
    ports:
      - '6379:6379'

  django:
    container_name: django_server
    image: my_first_image
    ports:
      - "8000:8000"
    links:
      - redis

networks:
  my-network:
    external: true