# Generated by Django 4.2 on 2023-04-27 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_orderitem_name_orderitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='user',
        ),
    ]
