# Generated by Django 4.2 on 2023-04-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_orderitem_image_remove_orderitem_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cancalCount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
